### ISSUE TITLE
Does this work on react-native?

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/babel-plugin-react-intl#91]
I'm trying to get this plugin to work on react-native, but I'm not succeeding.

.babelrc

        {
          "presets": [
            "react-native",
            "react-native-stage-0",
            "react-native-stage-0/decorator-support",
          ],
          "plugins": [
                ["react-intl", {
                  "messagesDir": "./build/i18n/messages/",
                  "enforceDescriptions": false
                 }]
            ]
        }

App.js

        'use strict';

        import React from 'react';
        import { Text } from 'react-native';
        import { config, styles } from './MSA';

        import { Provider } from 'react-redux';
        import { IntlProvider } from 'react-intl-redux';
        import ptLocaleDate from 'react-intl/locale-data/pt';
        import { addLocaleData } from 'react-intl';

        import language from './resources/i8n/msa.pt';

        import { MenuContext } from 'react-native-popup-menu';
        import UIContainer from './modules/navigation/components/UIContainer';
        import routez from './resources/routez';

        import configureStore from './store/configureStore';

        addLocaleData([
          ...ptLocaleDate
        ]);

        const store = configureStore({
          intl: {
            locale: config.locale,
            messages: language
          }
        });

        export default class Root extends React.Component {

            render() {
                return (
              <Provider store={store}>
                  <IntlProvider textComponent={Text} defaultLocale="pt">
                      <MenuContext>
                          <UIContainer
                              routes = {routez}
                          />
                      </MenuContext>
                  </IntlProvider>
              </Provider>
                );
            }
        }

I'm using FormattedMessage and @injectIntl => intl.formatMessage style messages. But I'm not seeing anything show up. The build directory is also not created.

I'm tried node 6.1.0 and 6.9.2. Not sure what to expect here in terms of result and / or errors.

**Comment by ericf** [comment]
It has nothing to do with React Native. It's just a Babel plugin which should operate normally within a Babel compile. Did you try just running `babel` CLI to make sure you have everything setup correctly?

**Comment by mschipperheyn** [comment]
Ok, yeah, uncertain what to expect here. 

When I run `babel --plugins react-intl`, it just seems to kind of hang and not do anything.

**Comment by ericf** [comment]
You'd need to provide a simplified example of the issue that I can run to help any further. I don't understand why it's not working for you via the Babel CLI.

**Comment by ericf** [comment]
This should now be fixed in 2.3.1.

**Comment by dstudzinski** [comment]
I have similar issue. I use plugin in version 2.3.0

My .babelrc
```
{
  "presets": ["react-native"],
  "plugins": [
    ["react-intl", {
      "messagesDir": "./messages/"
    }]
  ]
}
```

Part of my routes.js
```
const routesNames = defineMessages({
  settingsView: {
    id: 'routes.settingsView',
    description: 'Settings view title',
    defaultMessage: 'Settings'
  },
  newProcedureView: {
    id: 'routes.newProcedureView',
    description: 'New procedure view title',
    defaultMessage: 'New procedure'
  },
  proceduresListView: {
    id: 'routes.proceduresListView',
    description: 'Procedures list view title',
    defaultMessage: 'Procedures list'
  }
});
```

After `babel src` in cmd `messages/src/configs/routes.json` file is created with content:
```
[
  {
    "id": "routes.settingsView",
    "description": "Settings view title",
    "defaultMessage": "Settings"
  },
  {
    "id": "routes.newProcedureView",
    "description": "New procedure view title",
    "defaultMessage": "New procedure"
  },
  {
    "id": "routes.proceduresListView",
    "description": "Procedures list view title",
    "defaultMessage": "Procedures list"
  }
]
```

but when I try `react-native run-android` (and RN packager runs) nothing happens.  
My babelrc file is for sure used by RN because if I add some wrong line I get an error :)

**Comment by Druux** [comment]
Seems like it still doesn't work in 2.3.1 as well - the build directory wont be created. That means the messages wont be extracted. Any updates on that?

**Comment by kcouliba** [comment]
Hello, 
I'm using v.2.4.0. Still facing the same issue.
